# Generated by Django 2.2 on 2019-05-09 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally',
            name='goods_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='administer.Goods'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userorder',
            name='method',
            field=models.CharField(default='发货', max_length=32),
        ),
        migrations.AlterField(
            model_name='replenish',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administer.Goods'),
        ),
        migrations.AlterField(
            model_name='tally',
            name='t_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administer.Goods'),
        ),
    ]
