# Generated by Django 2.2 on 2019-05-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administer', '0002_auto_20190509_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tally',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administer.UserOrder'),
        ),
    ]
