# Generated by Django 2.2 on 2019-05-09 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administer', '0003_auto_20190509_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopstock',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administer.Goods'),
        ),
        migrations.AlterField(
            model_name='shopstock',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administer.Shop'),
        ),
    ]
