# Generated by Django 2.2 on 2019-05-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administer', '0005_auto_20190509_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally',
            name='t_type',
            field=models.CharField(max_length=32),
        ),
    ]
